import { prisma } from "@/lib/prisma";
import { generateReplyDraft } from "@/lib/ai-reply";
import { classifyReviewSafety } from "@/lib/review-safety";
import { sendGoogleReviewReply } from "@/lib/google-reply";
import { logReplyAudit } from "@/lib/reply-audit";

export async function tryAutoSendGoogleReplyForReview(reviewId: string): Promise<{
  autoSent: boolean;
  reason?: string;
  error?: string;
}> {
  const review = await prisma.review.findUnique({
    where: { id: reviewId },
    include: {
      location: {
        select: {
          id: true,
          googleLocationName: true,
          googleConnectionId: true,
          googleAutoReplyEnabled: true,
          googleAutoReplyThreshold: true,
          googleAutoReplyDailyCap: true,
          googleAutoReplyLastUsedAt: true,
          organizationId: true,
        },
      },
    },
  });

  if (!review) {
    return { autoSent: false, reason: "Review not found" };
  }

  // Check if auto-send is enabled
  if (!review.location.googleAutoReplyEnabled) {
    return { autoSent: false, reason: "Auto-send not enabled for this location" };
  }

  // Only auto-send Google reviews
  if (review.source !== "GOOGLE") {
    return { autoSent: false, reason: "Auto-send only supports Google reviews" };
  }

  // Don't auto-send if already sent
  if (review.replySentAt) {
    return { autoSent: false, reason: "Reply already sent" };
  }

  // Check rating threshold
  if (!review.rating || review.rating < review.location.googleAutoReplyThreshold) {
    return { autoSent: false, reason: `Rating ${review.rating} below threshold ${review.location.googleAutoReplyThreshold}` };
  }

  // Check daily cap
  if (review.location.googleAutoReplyDailyCap > 0) {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const sentTodayCount = await prisma.replyAuditLog.count({
      where: {
        locationId: review.location.id,
        action: "SENT_TO_GOOGLE",
        resultStatus: "SUCCESS",
        createdAt: {
          gte: today,
        },
      },
    });

    if (sentTodayCount >= review.location.googleAutoReplyDailyCap) {
      return { autoSent: false, reason: `Daily cap (${review.location.googleAutoReplyDailyCap}) reached` };
    }
  }

  // Generate reply if not already drafted
  let replyText = review.replyDraft;
  if (!replyText) {
    try {
      replyText = await generateReplyDraft({
        reviewerName: review.reviewerName,
        rating: review.rating,
        body: review.body,
      });
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : "AI generation failed";
      await logReplyAudit({
        reviewId,
        locationId: review.location.id,
        action: "DRAFT_GENERATED",
        resultStatus: "FAILED",
        errorMessage: errorMsg,
      });
      return { autoSent: false, error: errorMsg };
    }

    // Log draft generation
    await logReplyAudit({
      reviewId,
      locationId: review.location.id,
      action: "DRAFT_GENERATED",
      resultStatus: "SUCCESS",
      draftText: replyText,
      metadata: { autoGenerated: true },
    });
  }

  // Check safety
  const safety = classifyReviewSafety(replyText);
  if (safety.isRisky) {
    await logReplyAudit({
      reviewId,
      locationId: review.location.id,
      action: "SAFETY_BLOCKED",
      resultStatus: "BLOCKED",
      draftText: replyText,
      safetyClassification: safety,
      metadata: { autoSend: true },
    });
    return { autoSent: false, reason: `Safety check failed: ${safety.reason}` };
  }

  // Send to Google
  const sendResult = await sendGoogleReviewReply(reviewId, replyText);
  if (!sendResult.success) {
    await logReplyAudit({
      reviewId,
      locationId: review.location.id,
      action: "FAILED",
      resultStatus: "FAILED",
      draftText: replyText,
      errorMessage: sendResult.error,
      metadata: { autoSend: true, ...sendResult.metadata },
    });
    return { autoSent: false, error: sendResult.error };
  }

  // Update review with sent info
  const fallbackSender = await prisma.userMembership.findFirst({
    where: {
      organizationId: review.location.organizationId,
      status: "ACTIVE",
    },
    orderBy: [{ createdAt: "asc" }],
    select: { id: true },
  });

  await prisma.review.update({
    where: { id: reviewId },
    data: {
      replyDraft: replyText,
      sourceReplyText: replyText,
      replySentAt: sendResult.publishedAt,
      replySentByMembershipId: fallbackSender?.id ?? null,
    },
  });

  // Log successful send
  await logReplyAudit({
    reviewId,
    locationId: review.location.id,
    action: "SENT_TO_GOOGLE",
    resultStatus: "SUCCESS",
    draftText: replyText,
    metadata: { autoSend: true, ...sendResult.metadata },
  });

  // Update last used timestamp
  await prisma.location.update({
    where: { id: review.location.id },
    data: {
      googleAutoReplyLastUsedAt: new Date(),
    },
  });

  return { autoSent: true };
}
