ALTER TYPE "ReviewLinkEventType" ADD VALUE IF NOT EXISTS 'START_FROM_SCRATCH_SELECTED';
ALTER TYPE "ReviewLinkEventType" ADD VALUE IF NOT EXISTS 'MANUAL_WRITING_STARTED';
ALTER TYPE "ReviewLinkEventType" ADD VALUE IF NOT EXISTS 'MANUAL_REVIEW_COMPLETED';
ALTER TYPE "ReviewLinkEventType" ADD VALUE IF NOT EXISTS 'AI_DRAFT_ACCEPTED';
ALTER TYPE "ReviewLinkEventType" ADD VALUE IF NOT EXISTS 'AI_ASSIST_TOOL_USED';
